import { Mail, MapPin, Package, RadioTower, Send, ShieldCheck } from 'lucide-react';
import { CtaBand, PageIntro, PageMeta, PlaceholderSection, SectionLabel, StatusList } from '@/components/page-primitives';
import { SiteFooter } from '@/components/site-shell';

export function AboutPage() {
  return <main className="page-reveal"><PageMeta title="About GG Snacks" description="The GG Snacks about foundation from Jeddah." /><PageIntro eyebrow="02 / About GG Snacks" title={<>Origin<br /><span className="text-primary">pending.</span></>} detail="This is the place for the GG Snacks point of view, origin story, and team. We are keeping company facts open until the source material is ready." /><PlaceholderSection index="01" title="A local signal with global energy." description="Narrative placeholder — verified company story, founding details, and brand principles will be added here." accent="#35e6dc" /><section className="border-b border-white/10 py-16 sm:py-24"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><SectionLabel index="02">What belongs here</SectionLabel><StatusList items={['Brand story placeholder', 'Team and origin placeholder', 'Saudi / Jeddah context to be confirmed']} /></div></section><CtaBand title="See what is in the product signal." label="View products" href="/products" testId="link-about-products" /><SiteFooter /></main>;
}

export function QualityPage() {
  return <main className="page-reveal"><PageMeta title="Quality" description="The GG Snacks quality foundation." /><PageIntro eyebrow="03 / Quality" title={<>Made for<br /><span className="text-accent">repeat play.</span></>} detail="Quality is a system, not a badge. This shell is ready for the standards, sourcing, production, and verification details that define GG Snacks." /><section className="border-b border-white/10 py-16 sm:py-24"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:gap-24 lg:px-12"><div><SectionLabel index="01">Quality architecture</SectionLabel><h2 className="font-display text-5xl font-bold uppercase leading-[.9] sm:text-7xl">Proof over<br /><span className="text-primary">noise.</span></h2></div><div className="grid gap-3 sm:grid-cols-2"><div className="border border-white/10 bg-[#101317] p-6"><ShieldCheck className="text-primary" size={23} strokeWidth={1.5} aria-hidden="true" /><h3 className="mt-14 font-display text-3xl uppercase">Standards</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Information placeholder — details pending.</p></div><div className="border border-white/10 bg-[#101317] p-6"><RadioTower className="text-accent" size={23} strokeWidth={1.5} aria-hidden="true" /><h3 className="mt-14 font-display text-3xl uppercase">Traceability</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">Information placeholder — details pending.</p></div></div></div></section><CtaBand title="Keep exploring the signal." label="About GG Snacks" href="/about" testId="link-quality-about" /><SiteFooter /></main>;
}

export function DistributionPage() {
  return <main className="page-reveal"><PageMeta title="Distribution" description="The GG Snacks distribution foundation." /><PageIntro eyebrow="04 / Distribution" title={<>Put it<br /><span className="text-primary">in play.</span></>} detail="A distribution shell for future retail, food service, and partner pathways. Availability and commercial details are intentionally not specified yet." /><PlaceholderSection index="01" title="Built to travel." description="Distribution story placeholder — channels, territories, and partner information will be added when confirmed." accent="#ffbf4b" action={{ label: 'Start a conversation', href: '/contact', testId: 'link-distribution-contact' }} /><section className="border-b border-white/10 py-16 sm:py-24"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><SectionLabel index="02">Partner intake</SectionLabel><StatusList items={['Channel framework placeholder', 'Territory details placeholder', 'Commercial contact placeholder']} /></div></section><SiteFooter /></main>;
}

export function ContactPage() {
  return <main className="page-reveal"><PageMeta title="Contact" description="Contact GG Snacks — details are currently placeholders." /><PageIntro eyebrow="05 / Contact" title={<>Open<br /><span className="text-accent">channel.</span></>} detail="Contact details are not available yet. This page is a clear, ready-to-fill shell for future retail, distribution, press, and general enquiries." /><section className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 sm:py-24 lg:px-12"><div className="grid gap-4 md:grid-cols-3"><div className="border border-white/10 bg-[#101317] p-6"><MapPin size={22} className="text-primary" strokeWidth={1.5} aria-hidden="true" /><p className="mt-12 font-mono-brand text-[10px] uppercase tracking-[.16em] text-primary">Location</p><p className="mt-2 text-sm text-muted-foreground" data-testid="text-contact-location">Jeddah, Saudi Arabia</p></div><div className="border border-white/10 bg-[#101317] p-6"><Mail size={22} className="text-accent" strokeWidth={1.5} aria-hidden="true" /><p className="mt-12 font-mono-brand text-[10px] uppercase tracking-[.16em] text-accent">Email</p><p className="mt-2 text-sm text-muted-foreground" data-testid="text-contact-email">Placeholder — email not available</p></div><div className="border border-white/10 bg-[#101317] p-6"><Package size={22} className="text-primary" strokeWidth={1.5} aria-hidden="true" /><p className="mt-12 font-mono-brand text-[10px] uppercase tracking-[.16em] text-primary">Partnerships</p><p className="mt-2 text-sm text-muted-foreground" data-testid="text-contact-partnerships">Placeholder — details not available</p></div></div><div className="mt-12 border border-dashed border-white/15 bg-[#0d1013] p-6 sm:p-10"><div className="flex items-start gap-4"><Send size={20} className="mt-1 text-primary" aria-hidden="true" /><div><h2 className="font-display text-3xl uppercase">Contact form module</h2><p className="mt-2 max-w-lg text-sm leading-6 text-muted-foreground">Form wiring is intentionally deferred until a contact endpoint exists. No message will be submitted from this foundation pass.</p><button type="button" disabled data-testid="button-contact-placeholder" className="mt-6 cursor-not-allowed border border-white/15 px-5 py-3 text-xs font-bold uppercase tracking-[.14em] text-white/35">Form placeholder</button></div></div></div></section><SiteFooter /></main>;
}